export const initialFilterTime = {
  zero_to_three: false,
  three_to_six: false,
  six_to_twelve: false,
  twelve_to_eighteen: false,
  eighteen_to_twentyFour: false,
  greater_than_twentyFour: false,
};

// Mapping of keys to labels
export const filterTimeLabel = {
  zero_to_three: "0-3 months",
  three_to_six: "3-6 months",
  six_to_twelve: "6-12 months",
  twelve_to_eighteen: "12-18 months",
  eighteen_to_twentyFour: "18-24 months",
  greater_than_twentyFour: "Greater than 24 months",
};

export const sectorIcons = {
  "defence"  :   "Defence.svg",
    "aerospace"  :   "Aerospace.svg",
    "alcohol"  :   "Alcohol.svg'",
    "auto-ancillaries"  :   "Auto Ancillaries.svg",
    "automobile"  :   "Automobile.svg",
    "banks"  :   "Banks.svg",
    "bearings"  :   "Bearings.svg",
    "cables"  :   "Cables.svg",
    "capital-goods"  :   "Capital Goods.svg",
    "castings-forgings-fasteners"  :   "Castings.svg",
    "cement"  :   "Cement.svg",
    "ceramic-products"  :   "Ceramic.svg",
    "chemicals"  :   "Chemicals.svg",
    "education"  :   "Education.svg",
    "construction"  :   "Construction.svg",
    "consumer-durables"  :   "Consumer Durables.svg",
    "crude-oil-natural-gas"  :   "Crude Oil & Natural Gas.svg",
    "jewellery"  :   "Jewellery.svg",
    "diversified"  :   "Diversified.svg",
    "new-age-it"  :   "New Age IT.svg",
    "electronics"  :   "Electronics.svg",
    "entertainment"  :   "Entertainment.svg",
    "fertilizers"  :   "Fertilizers.svg",
    "finance"  :   "Finance.svg",
    "fmcg"  :   "FMCG.svg",
    "gas-distribution"  :   "Gas distribution.svg",
    "glass-glass-products"  :   "Glass & Glass Products.svg",
    "healthcare"  :   "Healthcare.svg",
    "hotels-restaurants"  :   "Hotels & Restaurants.svg",
    "infrastructure"  :   "Infrastructure Developers & Operators.svg",
    "insurance"  :   "Insurance.svg",
    "it"  :   "IT.svg",
    "logistics"  :   "Logistics.svg",
    "marine-port-services"  :   "Marine Port & Services.svg",
    "media"  :   "media.svg'",
    "mining-mineral-products"  :   "Mining & Mineral Products.svg",
    "miscellaneous"  :   "Miscellaneous.svg",
    "packaging"  :   "Packaging.svg",
    "paints"  :   "Paints.svg",
    "paper"  :   "Paper.svg",
    "pharmaceuticals"  :   "Pharmaceuticals.svg",
    "plastic-products"  :   "Plastic products.svg",
    "plywood-boards-laminates"  :   "Laminates.svg",
    "power-generation-distribution"  :   "Power Generation & Distribution.svg",
    "printing-stationery"  :   "Printing & Stationery.svg",
    "quick-service-restaurant"  :   "Quick Service Restaurant.svg",
    "railways"  :   "Railways.svg",
    "readymade-garments-apparels"  :   "Readymade Garments_ Apparels.svg",
    "investment-trusts"  :   "Investment Trusts.svg",
    "renewable"  :   "Renewable.svg",
    "real-estate"  :   "Real estate.svg",
    "refineries"  :   "Refineries.svg",
    "refractories"  :   "Refractories.svg",
    "retail"  :   "Retail.svg",
    "sanitaryware"  :   "Sanitaryware.svg",
    "ship-building"  :   "Ship Building.svg",
    "steel"  :   "Steel.svg",
    "sugar"  :   "Sugar.svg",
    "stock-investment-companies"  :   "Investment companies.svg",
    "telecom"  :   "Telecom.svg",
    "textiles"  :   "Textiles.svg",
    "trading"  :   "trading.svg",
    "tyres-ancillaries"  :   "Tyres & Ancillaries.svg",
    "holding-company"  :   "Holding company.svg",
}
